### ISSUE TITLE
no space for backup 

### ISSUE THREAD

**Issue by Bealze** [TS3Tools/TS3UpdateScript#102]
can i change location to my home directory instead of tmp

**Comment by Sebi94nbg** [comment]
The backup directories are now configureable with the release [5.8.0](https://github.com/TS3Tools/TS3UpdateScript/releases/tag/5.8.0):
https://github.com/TS3Tools/TS3UpdateScript/blob/77c36f7c93c0fc5745d3cf3b2000dbbb220e0983/configs/config.all#L4-L5

- `TEMP_BACKUP_DIR` => These backups get always automatically deleted, when the update was successful.
- `PERSISTENT_BACKUP_DIR` => These backups never get deleted, because there can be always an issue in the script, that it thinks, that everything went fine, but in real something went wrong.
