### ISSUE TITLE
Test Inform Online Clients Command

### ISSUE THREAD

**Issue by 7quit** [TS3Tools/TS3UpdateScript#110]
Hello,

I have a question, and that is, I executed the following command: **`./TS3UpdateScript --test-inform-online-clients`**.
But, when I execute this command, I get the following message, although users are on the TeamSpeak server and the admin password is correct.
![meldung](https://user-images.githubusercontent.com/45004106/128637858-5d48c1e4-63ca-495c-a505-93188b3c00a6.png)

**Comment by Sebi94nbg** [comment]
Hey,
mhmm, this should be an "INFO", not a "FAILED". So just "ignore" this. :D

The script generates a list of current connected clients. Afterwards, it pokes everyone one-by-one. This takes some time and in the mean time, clients can re-connect, disconnect and connect and then some clients might be not pokeable anymore and some will not be poked since they joined after the list of clients was generated.

The actual update would display you the same text / message, but as "information".

**Comment by 7quit** [comment]
Thank you ^^
