### ISSUE TITLE
TeamSpeak autostart question

### ISSUE THREAD

**Issue by 7quit** [TS3Tools/TS3UpdateScript#111]
Hello,

I have a question, is it bad that I use this TeamSpeak service?
Or do I have to pay attention to something about the UpdateScript or something?

My TeamSpeak Service Config:
![image](https://user-images.githubusercontent.com/45004106/128867293-d4e58afb-abf9-4013-a300-c103c8df7313.png)

**Comment by Sebi94nbg** [comment]
Hey,
Sorry, I was on vacation the last two weeks and only limited available.

In general, it should be compatible and working without any problems. You might only want to ensure, that it doesn't restart (start / stop / restart) the TeamSpeak instance when the TS3UpdateScript is currently updating the instance.

In systemd you can simply add a file-based condition. In your LSBInitScript you need to add some logic like this (NOT tested; only an example):
```shell
if [[ ! -f ${DIR}/.ts3updatescript.lock ]]; then
    su -c "${DIR}/ts3server_startscript.sh start"
else
    echo "The TS3UpdateScript is currently updating this instance. Aborted.";
fi
```

This `.ts3updatescript.lock` is only an empty file, so you can simply create it and test your changes of your LSBInitScript:
```shell
# Simulate update by the TS3UpdateScript
touch ${DIR}/.ts3updatescript.lock

# Test your changes#
# Should report that the TS3UpdateScript is currently updating this instance and that it did nothing
service teamspeak3 stop
service teamspeak3 start
service teamspeak3 restart

# or
/etc/init.d/teamspeak3 stop
/etc/init.d/teamspeak3 start
/etc/init.d/teamspeak3 restart

# End simulation of the update by the TS3UpdateScript
rm ${DIR}/.ts3updatescript.lock
```

You can implement such a logic for each single case or you check it before even checking the cases and exit the LSBInitScript earlier - before reaching the cases.

See https://github.com/TS3Tools/TS3UpdateScript#hint-systemd for further information.

PS: LSBInitScripts are deprecated since years (when I remember correct since 2015). Instead you should use systemd.
