### ISSUE TITLE
Script can't update

### ISSUE THREAD

**Issue by twyK** [TS3Tools/TS3UpdateScript#15]
```
Please wait... Script is working...

Performing self-tests as preventive measures against possible failures                  [ OK ]

Collecting necessary information for further tasks                                      [ OK ]

All collected information were validated successfully as preventive measures against pos[ INFO ]ilures
1 TeamSpeak 3 server instance found...

Collecting as much as possible information for TeamSpeak 3 server instance '/home/twyk/ts3'
1 instance for update process...

Following instance needs an update, but is stopped and not touched by the script: /home/twyk/ts3 (Installed Version: 3.0.11.4)

Cleaning up...

Summary of measured execution time for each step
Total script: 8s
Self-Test: 4s
Collecting Information: 4s
Validation: 0s
Execution Mechanism: 0s
Cleanup: 0s
```

But the server is running...
@Sebi94nbg

**Comment by xxJeevesxx** [comment]
I had this same problem. It was a permissions problem for me. Double check your folder permissions...


Martin

**Comment by Sebi94nbg** [comment]
Hi @twyK,
Hi @xxJeevesxx,

thanks for your feedback.

As @xxJeevesxx already mentioned, please check the permissions. The script will start and stop your TS3 server instance as this user, which owns the file "ts3server_startscript.sh". If this file is owned by the user "teamspeak" and you've started the instance as root for example, you have one problem: The user teamspeak can't stop the instance, because the script "ts3server_startscript.sh" is unable to check the ts3server.pid file due to less permissions.

Well... The solution is to stop your instance, login as user "teamspeak" (in this example) and start your instance normal. This will create the file "ts3server.pid" with file permissions owned by the user "teamspeak".

If you can't start your instance as user "teamspeak", you need to check, if the root directory permissions are owned by "teamspeak" or root. If it's owned by root, your user "teamspeak" does not have any write permissions and this will cause, that your instance can't start properly, because the file "ts3server.pid" can't written to the filesystem.

After this, the script should be able to get the correct status ("Server is running") and run an update.

Please come back to me, if you've any feedback.


Best Regards,
Sebastian

**Comment by Sebi94nbg** [comment]
I'll close this due no feedback. Please come back, if you have any feedback. Thanks!
