### ISSUE TITLE
Script fails to find correct server within recursive directory.

### ISSUE THREAD

**Issue by techjwalker** [TS3Tools/TS3UpdateScript#22]
As an example, if you have a TS3 server in "/home/teamspeak" and another in "/home/teamspeak/home/teamspeak", which can happen if you've just unzipped a root-oriented backup within the user folder as I had, the script will find only the further recursive server and not the other, and will fail to update.

**Comment by Sebi94nbg** [comment]
The script detects all instances. Also such nested ones.

Due it is searching recursive, it will find the deeper instance first and will return this as first found instance for an update process.

I've tested this right now and it detects every instance as it should:
```
/home/teamspeak/home/teamspeak/
/home/teamspeak/
/home/ts3/teamspeak3-server_linux_amd64/
```
In every above path is one instance installed.

In your case, I would fix the backup deployment issue, because if you're creating a root-oriented backup, it also should place it to exact this path and not to a sub-path, that it appears twice.

If you want to be able to find all instances, you will need the Hoster license for this script: [Readme.md#Script Licenses](https://github.com/TS3Tools/TS3UpdateScript#script-licenses)
