### ISSUE TITLE
download link ?

### ISSUE THREAD

**Issue by LoloLaurentiu** [TS3Tools/TS3UpdateScript#38]
I don't find any download at http://addons.teamspeak.com/directory/tools/miscellaneous/Script-Automated-TeamSpeak-3-update-with-version-checker.html or from GitHub.com: https://github.com/TS3Tools/TS3UpdateScript/

and I see the latest Release https://github.com/TS3Tools/TS3UpdateScript/releases 4.3.1

**Comment by mightyBroccoli** [comment]
Terminal: `git clone https://github.com/TS3Tools/TS3UpdateScript.git`
`cd TS3UpdateScript`
`./TS3UpdateScript`

**Comment by LoloLaurentiu** [comment]
do I have to change the LATEST_STABLE_RELEASE=3.0.12.4 in the config.all file ?

**Comment by Sebi94nbg** [comment]
Thanks @mightyBroccoli !

@LoloLaurentiu : No, you haven't. It's just used to set a static version of release. By default, it's updating to the latest stable version of release.

**Comment by LoloLaurentiu** [comment]
I get this message every time I try to update

Following instance needs an update, but is stopped and not touched by the script: /usr/local/teamspeak (Installed Version: 3.0.12.4)
Cleaning up...

**Comment by mightyBroccoli** [comment]
Sometimes the error occures when you use the script with a user which does not have all permissions needed to move/ copy or write files.

**Comment by LoloLaurentiu** [comment]
well I executed the command as root

**Comment by Sebi94nbg** [comment]
Yes, otherwise the script wouldn't work. The script was developed to work only as root user.

@mightyBroccoli means, that the user/owner of the ts3server_startscript.sh is not able to stop/start the server with his permissions, due of wrong permissions.

This command is used by the script to start/stop the server:
`su -s $(which bash) -c "cd $1 && ./ts3server_startscript.sh status && cd - > /dev/null" - USER`

The owner of the file "ts3server_startscript.sh" will be used as "USER".

**Comment by Sebi94nbg** [comment]
Any news, @LoloLaurentiu ? Or can we close it?

**Comment by Sebi94nbg** [comment]
Closed, due of no further feedback.
