### ISSUE TITLE
Position of "--inform-online-clients" argument prevents fetching of the current version

### ISSUE THREAD

**Issue by slayit** [TS3Tools/TS3UpdateScript#6]
Hi, if I'm using the "--inform-online-clients" argument as the second argument, the script is no longer able to fetch the currently installed TS3 version. If I write it last, it works.

Script Version: 3.11.7 (2015-01-18)

Working command "./TS3UpdateScript.sh --check --delete-old-logs --keep-backups --inform-online-clients":

    Latest Stable Release   : 3.0.11.2
    Installed Release       : 3.0.11.2 (Build: 1418654632)
    Installed Architecture  : amd64
    Installed Binary        : Linux

Not working "./TS3UpdateScript.sh --check --inform-online-clients --delete-old-logs --keep-backups":

    Latest Stable Release   : 3.0.11.2
    Installed Release       : Unknown (Build: Unknown)
    Installed Architecture  : amd64
    Installed Binary        : Unknown

There were two error lines posted in the execution log:

    Informing online clients... This may take a while.
    ./TS3UpdateScript.sh: line 1100: [: missing `]'
    ./TS3UpdateScript.sh: line 1102: [: missing `]'
    Stopping the TeamSpeak 3 server..done

It is to note that this seems to be the only problem. The update process itself works, it just wants to update every time the script is running because it can't detect the most recent version.

Edit: Can't answer anymore. This conversation is locked to collaborators only.

**Comment by Sebi94nbg** [comment]
Hi,
thank you for your interest in my script and this information.

Are you sure that you are not banned by the TS3 server? With the parameter "--inform-online-clients", the server will detect the release, build and binary with the ServerQuery command "version" as ServerQuery guest. While a update process, the script will reconnect more times as ServerQuery to execute some commands like "sending pokes" and "version detection".

If you run this script to much within a specific time the server may bann you in case of flood detection/prevention. I've tested both commands you have provided and they are always working on my test machines/server.

The two errors with the missing `]' is not relevant, because the whole script is still working correct as you already said. But thank you for this information. I've already fixed this in the new version.
