### ISSUE TITLE
No documentation available on .password-file

### ISSUE THREAD

**Issue by Refalm** [TS3Tools/TS3UpdateScript#60]
There is no documentation available when confronted with this error:
`Wrong serveradmin password. Please set the correct one here: /opt/teamspeak/.password-file`

On a personal note, I don't know how to continue with this script.

**Comment by Sebi94nbg** [comment]
There is no documentation available, because it already says everything. :)

Well... Using telnet / Psychokiller's Webinterface / YatQA or anything similar, you can login using your ServerQuery login, right?

The default global "admin" is always called "serveradmin". The script requires the password of this user / login to collect some information and/or poke clients.

You need to save your `ServerQuery password` for the user `serveradmin` in the file `/opt/teamspeak/.password-file`.

**Comment by Sebi94nbg** [comment]
Is there anything still open @Refalm or could I help you?

**Comment by Sebi94nbg** [comment]
Closed due no feedback.
