### ISSUE TITLE
need a non-root switch

### ISSUE THREAD

**Issue by idlenexusgaming** [TS3Tools/TS3UpdateScript#67]
This is more of a request/suggestion than an issue. For folks running linux hosts where, for whatever reason, they don't have or wish to utilize (for security) root access for teamspeak and this script, it would be useful to have a switch that bypasses all the things that would require root. After the system has all the dependencies in place, there should be no need to run as root every time. I understand the need for it in the case with multiple accounts and multiple teamspeak services and am not suggesting the script be defanged of sudo. I only suggest that there be an option to skip the root check and the steps that require it.

Alternative, it would be useful to outline, for security reasons every task that requires root so that less script savvy people concerned about this can make informed decisions for using it. Cheers.

**Comment by Sebi94nbg** [comment]
Thanks for your FR or more suggestion.

I understand, what you want, but I don't believe, that I can update the script like you want.

I've start developing this script and always asked myself: What are the best ways / solutions to do some tasks in the script. I've tried to avoid the root user, but it wasn't possible for some tasks. (See https://github.com/TS3Tools/TS3UpdateScript#requirements)

Even the licensing feature is only working with root permissions, because it generates a unique license key based on the server information and stores this information in the filesystem. The result (the readable key) is saved in the same directory like the script.

Due of the licenses of this script, it also needs to check somehow, if the same script is may executed again for a different TeamSpeak 3 instance. Only root is able to check all directories...

Well... I'll leave this FR / Enhancement open for now. I'll check this out with the new major release.

I'm going to fully cleanup the script, that it looks like the [TS3Monitor](https://github.com/TS3Tools/TS3Monitor/tree/master/fncs) and there, I'll also finish/solve the issues #49  and #55.

**Comment by hitmany** [comment]
+1 we need just auto update script. Without human activity. And you asking about root \, thats but
My linux server was hacked due teamspeak outdated. Root is super unsecure
Change your license codes to server based(just register licenses by IP, how TS3 team is do it)

Anyway if you not agree noone will install your script

**Comment by Sebi94nbg** [comment]
I'll close this issue now, because there is no workaround to scan the entire server for available TeamSpeak 3 server instances without root permissions. root permissions will be always required.

I'm trained and familiar with Linux/Unix systems, permissions, hardening and so on. This script will only do stuff for updating TeamSpeak instances and keeping their permissions correct. The script will never ever do anything, what could damage your server. This just confirms the implementation of the best practices analyzer (BPA): It checks the files and permissions and warns the user, if there is anything, what could be changed to improve or secure the TeamSpeak server.

Registering the license only IP based is the worst idea ever, because everybody knows, that IPs can be easily spoofed and as soon as you get a new IP address, somebody else - who would get your old IP address - would have your license.

I believe, that this is the most used script to update TeamSpeak instances. To be honest, I don't know of any other script that is as powerful as this one and does the job so well. Years ago there was an update script with around 50 lines of code that updated the TeamSpeak instance without root privileges. However, this was very static and did not add any value:
- Always the same download, so always the same update (e.g. to version 3.12.0)
- No automatic detection of anything (paths, permissions, latest TeamSpeak 3 server version, etc. had to be entered manually each time)
- No support of beta version updates
- No checks to see if anything could already cause an error before the update
- No checks if the update worked. It just stupidly performed an update.

That the TS3UpdateScript is appreciated is confirmed by the statistics and customers who actively request support, buy licenses and donate.
