### ISSUE TITLE
Server needs an update, but is stopped and not touched by the script

### ISSUE THREAD

**Issue by chrissd23** [TS3Tools/TS3UpdateScript#90]
Hello,
I am using 5.6.5 (2018-05-15) of the updater

Why does the script stop the update process? Is there any logs I can examine and post here to resolve this issue?
Thanks

Performing self-tests as preventive measures against possible failures                                                                             
cp: Aufruf von stat für ».ts3updatescript“ nicht möglich: Datei oder Verzeichnis nicht gefunden
chown: Zugriff auf »/etc/bash_completion.d/ts3updatescript“ nicht möglich: Datei oder Verzeichnis nicht gefunden
Collecting necessary information for further tasks                                                                                                 
All collected information were validated successfully as preventive measures against possible failures                                             [ INFO ]
1 TeamSpeak 3 server instance found...
Collecting as much as possible information for following TeamSpeak 3 server instance: /usr/local/bin/teamspeak3-server_linux_amd64
1 instance for update process...

Following instance needs an update, but is stopped and not touched by the script: /usr/local/bin/teamspeak3-server_linux_amd64 (Installed Version: 3.0.11.2)

**Comment by Sebi94nbg** [comment]
Hi @chrissd23 ,
first of all: This error message about the missing file / directory can be fixed by simply downloading this missing file and putting it to the root directory of the TS3UpdateScript: https://github.com/TS3Tools/TS3UpdateScript/blob/master/.ts3updatescript

The script will install the bash completion and if your system supports bash completion, you can use the TAB key to complete half-written commands. Example:

`./TS3UpdateScript --check --del[Tab]`

...will automatically complete it to this:

`./TS3UpdateScript --check --delete-old-logs`

Regarding your main problem:
> Following instance needs an update, but is stopped and not touched by the script: [...]

The script checks the files permission of the ts3server_startscript.sh file in the TeamSpeak server root directory. If this file is owned by the user "teamspeak" for example, the script logs in as user "teamspeak" and executes the status command of the startscript. If it's returning "Server is running", all is fine. If it's returning anything else, the script will abort with the above message as the TS3UpdateScript will only update TeamSpeak server instances, which are working and online. Otherwise the script can't verify, if the current instance is even working like it is and later, after the update, it would need to verify, if it's still working or not. Simply starting and stopping instances would be a solution, but as this could cause other issues due of licensing, the TS3UpdateScript will not do this.

So please check the file permissions:
```
$ ls -lh /usr/local/bin/teamspeak3-server_linux_amd64/ts3server_startscript.sh
-rwxr-xr-x 1 teamspeak users 2,7K Sep  3 09:41 /usr/local/bin/teamspeak3-server_linux_amd64/ts3server_startscript.sh
```

Log in as the user shown in this output - in this case `teamspeak`:
`su - teamspeak`

Change into the correct directory, if you're not already there:
`cd /usr/local/bin/teamspeak3-server_linux_amd64/`

Check, what the startscript is returning:
```
$ ./ts3server_startscript.sh status
Server is running
```

If this is not returning the same result as here, you need to stop your TeamSpeak 3 server instance and start it as the correct user.

Please make sure, that all files are owned by the same user as the `ts3server_startscript.sh` is.
